import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { BlogEntry, queryBlogDatabase } from "../utils/notion-client";
import NextLink from "next/link";

interface PageProps {
  blogEntries: BlogEntry[];
}

export const getStaticProps: GetStaticProps<PageProps> = async () => {
  const blogEntries = await queryBlogDatabase();

  return {
    props: {
      blogEntries,
    },
  };
};

const Home: NextPage<PageProps> = ({ blogEntries }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>My Blog Posts</h1>
        <ul>
          {blogEntries.map(({ id, title, slug, date }) => (
            <li key={id}>
              <NextLink href={`/blog/${slug}`} passHref>
                {`${title} (${date})`}
              </NextLink>
            </li>
          ))}
        </ul>
      </main>
    </div>
  );
};

export default Home;
